include:
  - board: nice_nano_v2
    shield: microdox_left
  - board: nice_nano_v2
    shield: microdox_right
  - board: seeeduino_xiao_ble
    shield: microdox_dongle
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: nice_nano_v2
    shield: settings_reset
